# Generated by Django 3.2.6 on 2021-08-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('industry_name', models.CharField(max_length=50)),
                ('bank_id', models.IntegerField()),
                ('account_id', models.IntegerField()),
                ('check_digit', models.IntegerField()),
                ('is_valid_card', models.BooleanField(default=False)),
            ],
        ),
    ]
