# Generated by Django 3.2.6 on 2021-08-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validateCard', '0002_alter_validatecard_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validatecard',
            name='card_number',
            field=models.CharField(max_length=30),
        ),
    ]
