# Generated by Django 3.2.6 on 2021-08-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validateCard', '0004_auto_20210813_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validatecard',
            name='card_number',
            field=models.CharField(max_length=20),
        ),
    ]
